//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change the password!.
        /// </summary>
        internal static string CHANGE_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client already has a product with that name!.
        /// </summary>
        internal static string DUPLICATE_WARE_TITLE_BY_THE_USER {
            get {
                return ResourceManager.GetString("DUPLICATE_WARE_TITLE_BY_THE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid credentials!.
        /// </summary>
        internal static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token!.
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match!.
        /// </summary>
        internal static string PASSWORDS_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORDS_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding user role!.
        /// </summary>
        internal static string ROLE_FIND_ERROR {
            get {
                return ResourceManager.GetString("ROLE_FIND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart is empty!.
        /// </summary>
        internal static string THE_CART_IS_EMPTY {
            get {
                return ResourceManager.GetString("THE_CART_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart not found!.
        /// </summary>
        internal static string THE_CART_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_CART_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category with this name has already been created!.
        /// </summary>
        internal static string THE_CATEGORY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("THE_CATEGORY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category not found!.
        /// </summary>
        internal static string THE_CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name of the characteristic in the product!.
        /// </summary>
        internal static string THE_CHARACTERISTIC_NAME_DUPLICATE {
            get {
                return ResourceManager.GetString("THE_CHARACTERISTIC_NAME_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a user with this email!.
        /// </summary>
        internal static string THE_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("THE_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity role not found!.
        /// </summary>
        internal static string THE_IDENTITY_ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_IDENTITY_ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send mail!.
        /// </summary>
        internal static string THE_MAIL_SENDING_ERROR {
            get {
                return ResourceManager.GetString("THE_MAIL_SENDING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new information is the same as the previous one!.
        /// </summary>
        internal static string THE_NEW_INFO_IS_THE_SAME_AS_PREVIOUS {
            get {
                return ResourceManager.GetString("THE_NEW_INFO_IS_THE_SAME_AS_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has already been confirmed!.
        /// </summary>
        internal static string THE_ORDER_ALREADY_CONFIRMED {
            get {
                return ResourceManager.GetString("THE_ORDER_ALREADY_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has already been picked!.
        /// </summary>
        internal static string THE_ORDER_ALREADY_PICKED {
            get {
                return ResourceManager.GetString("THE_ORDER_ALREADY_PICKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order not confirmed!.
        /// </summary>
        internal static string THE_ORDER_NOT_CONFIRMED {
            get {
                return ResourceManager.GetString("THE_ORDER_NOT_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order not found!.
        /// </summary>
        internal static string THE_ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous information is the same!.
        /// </summary>
        internal static string THE_PREVIOUS_INFO_IS_THE_SAME {
            get {
                return ResourceManager.GetString("THE_PREVIOUS_INFO_IS_THE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user not found!.
        /// </summary>
        internal static string THE_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is already in the cart!.
        /// </summary>
        internal static string THE_WARE_IS_ALREADY_IN_THE_CART {
            get {
                return ResourceManager.GetString("THE_WARE_IS_ALREADY_IN_THE_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product not found!.
        /// </summary>
        internal static string THE_WARE_NOT_FOUND {
            get {
                return ResourceManager.GetString("THE_WARE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
